# go to this file path and run command --> docker-compose up -d
# to scale the application run command --> docker-compose up -d --scale deploymentproject=2
# to scale the application and build again run command --> docker-compose up -d --build --scale deploymentproject=2
# docker ps
# docker-compose down
version: "3"

services:
  deploymentproject: # name of service
    build:
      context: . # path of Dockerfile that is present project is this case same directory
    ports:
      - "5000"
      #- "5000:5000"  # 'HOST:CONTAINER' format <HOST or system port : docker container port>
    restart: always
    depends_on:
      - mysql_db

  nginx: # service name
    image: nginx:latest # latest nginx image
    container_name: nginx_service
    volumes: # path of config files
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # map system nginx.conf file to nginx image configuration file
    depends_on: # asks nginx to wait till deploymentproject instances starts
      - deploymentproject
    restart: always
    ports:
      - "8080:8080" # map <port 80 on my system/localhost to port 80 of docker nginx container>

  mysql_db:
    image: mysql:latest
    container_name: mysql_service
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=coaching
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
